spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri: lb://customer-service
          predicates: 
            - Path= /api/customers/**
        - id: r2
          uri: lb://invoice-service
          predicates: 
            - Path= /invoices/**
